site_name: Corewar.io Documentation
repo_url: https://github.com/gareththegeek/corewar
pages:
- Home: index.md
- Guide to Corewar: 
   - Intro: corewar/index.md
   - Core: corewar/core.md
   - Warriors: corewar/warriors.md
   - Loader: corewar/loader.md
- Redcode Reference:
   - Intro: redcode/index.md
   - Execution: redcode/execution.md
   - Operands: redcode/operands.md
   - Opcodes: redcode/opcodes.md
   - Modifiers: redcode/modifiers.md
   - Addressing Modes: redcode/addressing_modes.md
   - Org and End: redcode/org.md
   - Parser: redcode/parser.md
   - Labels: redcode/labels.md
   - Preprocessor: redcode/preprocessor.md
   - Comments: redcode/comments.md
   - Metadata: redcode/metadata.md
- Developer Reference: developer/index.md
theme: readthedocs