on:
  release:
    types: [created]

name: corewar-hills-service azure docker deploy

env:
  APP_NAME: corewar-hills-service
  REGISTRY: corewar.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.HILLS_SERVICE_AZURE_CREDENTIALS }}
    
    - name: 'Login to Azure Docker CR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: 'Build Docker Image'
      working-directory: ./packages/corewar-hills-service
      run: |
        docker build . -t ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} 
    
    - name: 'Deploy Docker Image'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.APP_NAME }}'
        images: '${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}'